//public int hashCode():
//			Every object has unique number which is generated by JVM called as hashCode

package com.object;

public class Example1 {

	public static void main(String[] args) {
		Example1 example1 = new Example1();
		Example1 example2 = new Example1();
		System.out.println(example1.hashCode());
		System.out.println(example2.hashCode());
	}
}
